### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by JorisDeRidder42** [deliton/eldenring-api#24]
On my elden ring project I wanna add pagination. But how can I know what the last page is to check that my currentPage is not the lastPage?

Thanks alot, btw well done.

**Comment by deliton** [comment]
Hello @JorisDeRidder42 ! In order to use pagination you can make use of query parameters like:
![image](https://user-images.githubusercontent.com/47995046/216698816-5c3f0d4f-155f-46ee-8864-603708fd7fa8.png)

So in order to discover if you're in the last page you need to calculate that in your frontend based on the parameter `total` present in the API response. So for example if you make the following request: https://eldenring.fanapis.com/api/ammos?limit=10&page=2

You're gonna get the following metadata:
```JSON
{
"success": true,
"count": 10,
"total": 53,
}
```

So the formula for calculating the max number of pages is: ` total / limit` so in this case is ` 53 / 10 = 5.3` so we should round to `6 pages`

**Comment by JorisDeRidder42** [comment]
Thank you ^^
